name: test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            os: ubuntu-latest
            go-version: 'stable'
          - name: mac
            os: macos-latest
            go-version: 'stable'
          - name: windows
            os: windows-latest
            go-version: 'stable'
          - name: ubuntu go 1.12
            os: ubuntu-latest
            go-version: '1.12.x'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: go test -v
      - run: cd hjson-cli && go build
      - if: runner.os == 'Linux'
        run: hjson-cli/hjson-cli assets/comments_test.hjson | diff assets/sorted/comments_result.hjson -
      - if: runner.os == 'Linux'
        run: hjson-cli/hjson-cli -j assets/comments_test.hjson | diff assets/sorted/comments_result.json -
      - if: runner.os == 'Linux'
        run: hjson-cli/hjson-cli -preserveKeyOrder assets/comments_test.hjson | diff assets/comments_result.hjson -
      - if: runner.os == 'Linux'
        run: hjson-cli/hjson-cli -j -preserveKeyOrder assets/comments_test.hjson | diff assets/comments_result.json -
